from django.db import models

# Create your models here.
class issue(models.Model):
    GameId=models.IntegerField(verbose_name="游戏Id" , null=True)
    AreaId=models.IntegerField(verbose_name="区Id" ,null=True)
    Browser=models.CharField(verbose_name="浏览器" , max_length=50,null=True)
    BrowserVersion=models.CharField(verbose_name="浏览器版本号" , max_length=50,null=True)
    IssueNum=models.IntegerField(verbose_name="问题类型编号",null=True)
    IssueRemark=models.TextField(verbose_name="问题备注" , null=True)
    Platform=models.IntegerField(verbose_name="系统来源",null=True)
    SndaId=models.CharField(verbose_name="账号唯一标识" , max_length=50,null=True)
    Passport=models.CharField(verbose_name="用户输入账号" , max_length=50,null=True)
    RoleId=models.IntegerField(verbose_name="角色Id" ,null=True)
    RoleName=models.CharField(verbose_name="角色名称" , max_length=50,null=True)
    PicUrl=models.TextField(verbose_name="图片地址" ,null=True)
    CreateTime=models.DateTimeField(verbose_name="提问时间" ,null=True)
    Crucial=models.IntegerField(verbose_name="事件类型",null=True)
    Channel=models.IntegerField(verbose_name="渠道来源",null=True)
    UpgradeRemark=models.TextField(verbose_name="升级备注" , null=True)
    UpgradeRemark_sec=models.TextField(verbose_name="二次升级备注" , null=True)
    UpgradeTime=models.DateTimeField(verbose_name="升级时间" ,null=True)
    UpgradeTime_sec=models.DateTimeField(verbose_name="二次升级时间" ,null=True)
    FinalReplier=models.IntegerField(verbose_name="最终处理人",null=True)
    IsRead=models.IntegerField(verbose_name="用户是否阅读",null=True)
    System=models.CharField(verbose_name="系统来源名称" , max_length=150,null=True)
    ChannelName=models.CharField(verbose_name="渠道（平台）名称 " , max_length=50,null=True)
    DeviceModel=models.CharField(verbose_name="设备型号 " , max_length=50,null=True)
    OpenId=models.CharField(verbose_name="CP用户账号 " , max_length=50,null=True)
    DeviceId=models.CharField(verbose_name="设备号 " , max_length=50,null=True)
    UntiyDeviceId=models.CharField(verbose_name="Unity设备号 " , max_length=50,null=True)
    CPU=models.CharField(verbose_name="处理器型号 " , max_length=50,null=True)
    MemSize=models.CharField(verbose_name="内存大小 " , max_length=50,null=True)
    GraphicLv=models.CharField(verbose_name="图形硬件支持的ShaderLevel " , max_length=50,null=True)
    NetEnv=models.CharField(verbose_name="网络环境(Wifi/Moblie) " , max_length=50,null=True)
    Resolution=models.CharField(verbose_name="屏幕分辨率 " , max_length=50,null=True)