# Generated by Django 2.1.7 on 2019-07-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('depId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='CommonApps.department')),
            ],
        ),
    ]
