# Generated by Django 2.1.7 on 2019-08-01 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganeID', models.IntegerField(verbose_name='游戏Id')),
                ('gameName', models.CharField(max_length=50, verbose_name='游戏名称')),
                ('gameType', models.CharField(max_length=20, verbose_name='游戏类型')),
                ('isFlag', models.IntegerField(default=0, verbose_name='是否有效')),
                ('creatTime', models.IntegerField(default=datetime.datetime.now, verbose_name='更新时间戳')),
            ],
        ),
    ]
