# Generated by Django 2.1.7 on 2019-08-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameConfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gameConfig',
            new_name='gameinfo',
        ),
    ]
