# Generated by Django 2.1.7 on 2019-08-03 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameConfig', '0002_auto_20190802_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='creatTime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='更新时间戳'),
        ),
    ]
