# Generated by Django 2.1.7 on 2019-08-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameId', models.CharField(max_length=50, verbose_name='游戏Id')),
                ('AreaId', models.CharField(max_length=50, verbose_name='区Id')),
                ('Browser', models.CharField(max_length=50, verbose_name='浏览器')),
                ('BrowserVersion', models.CharField(max_length=50, verbose_name='浏览器版本号')),
                ('IssueNum', models.IntegerField(verbose_name='问题类型编号')),
                ('IssueRemark', models.CharField(max_length=255, verbose_name='问题备注')),
                ('Platform', models.IntegerField(verbose_name='系统来源')),
                ('SndaId', models.CharField(max_length=50, verbose_name='账号唯一标识')),
                ('Passport', models.CharField(max_length=50, verbose_name='用户输入账号')),
                ('RoleId', models.CharField(max_length=50, verbose_name='角色Id')),
                ('RoleName', models.CharField(max_length=50, verbose_name='角色名称')),
                ('PicUrl', models.CharField(max_length=255, verbose_name='图片地址')),
                ('CreateTime', models.DateTimeField(verbose_name='提问时间')),
                ('Crucial', models.IntegerField(verbose_name='事件类型')),
                ('Channel', models.IntegerField(verbose_name='渠道来源')),
                ('UpgradeRemark', models.CharField(max_length=255, verbose_name='升级备注')),
                ('UpgradeRemark_sec', models.CharField(max_length=255, verbose_name='二次升级备注')),
                ('UpgradeTime', models.DateTimeField(verbose_name='升级时间')),
                ('UpgradeTime_sec', models.DateTimeField(verbose_name='二次升级时间')),
                ('FinalReplier', models.IntegerField(verbose_name='最终处理人')),
                ('IsRead', models.IntegerField(verbose_name='用户是否阅读')),
                ('System', models.CharField(max_length=150, verbose_name='系统来源名称')),
                ('ChannelName', models.CharField(max_length=50, verbose_name='渠道（平台）名称 ')),
                ('DeviceModel', models.CharField(max_length=50, verbose_name='设备型号 ')),
                ('OpenId', models.CharField(max_length=50, verbose_name='CP用户账号 ')),
                ('DeviceId', models.CharField(max_length=50, verbose_name='设备号 ')),
                ('UntiyDeviceId', models.CharField(max_length=50, verbose_name='Unity设备号 ')),
                ('CPU', models.CharField(max_length=50, verbose_name='处理器型号 ')),
                ('MemSize', models.CharField(max_length=50, verbose_name='内存大小 ')),
                ('GraphicLv', models.CharField(max_length=50, verbose_name='图形硬件支持的ShaderLevel ')),
                ('NetEnv', models.CharField(max_length=50, verbose_name='网络环境(Wifi/Moblie) ')),
                ('Resolution', models.CharField(max_length=50, verbose_name='屏幕分辨率 ')),
            ],
        ),
    ]
