# Generated by Django 2.1.7 on 2019-08-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_issue', '0005_auto_20190803_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='AreaId',
            field=models.IntegerField(null=True, verbose_name='区Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='GameId',
            field=models.IntegerField(null=True, verbose_name='游戏Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='IssueRemark',
            field=models.TextField(null=True, verbose_name='问题备注'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='PicUrl',
            field=models.TextField(null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='RoleId',
            field=models.IntegerField(null=True, verbose_name='角色Id'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='UpgradeRemark',
            field=models.TextField(null=True, verbose_name='升级备注'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='UpgradeRemark_sec',
            field=models.TextField(null=True, verbose_name='二次升级备注'),
        ),
    ]
